add missing tag of Gfarm version 2.5.8.3, released on 2014-10-02

diff --git a/gftool/config-gfarm/config-gfarm.in b/gftool/config-gfarm/config-gfarm.in
--- a/gftool/config-gfarm/config-gfarm.in
+++ b/gftool/config-gfarm/config-gfarm.in
@@ -30,7 +30,6 @@ fi
 BACKEND_TYPE=$backend_default
 
 PRIVATE_MODE=false
-PRIVATE_MODE_FOR_DEBIAN=false
 
 #
 #
@@ -82,13 +81,61 @@ else
 	exit 1
 fi
 
-. $config_dir/config-gfarm.common
-
 # load backend-dependent functions. should be done after shell detection above.
 for i in $backend_all
 do
   . $config_dir/config-gfarm.$i
 done
+
+gen_passwd()
+{
+	chars="=.0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
+
+	if [ -r /dev/urandom ]; then
+		# enough entropy, use 258bit(=log2(64)*43) key
+
+		dd if=/dev/urandom bs=44 count=1 2>/dev/null | od -d |
+		$awk '
+		BEGIN{
+			chars="'"$chars"'"
+			k=length(chars)
+			chars_per_word=2
+			l=43 # 43 characters, 256bits/log2(64) = 42.666
+		}
+		{
+			for (i = 2; i <= NF; i++) {
+				r = $i
+				for (j = 0; j < chars_per_word; j++) {
+					if (l <= 0)
+						exit
+					printf "%c", substr(chars, r%k + 1, 1)
+					r /= k
+					--l
+				}
+			}
+		}
+		END {
+			printf "\n"
+		}'
+	else
+		# 32bit entropy due to the seed, use 66bit(=log2(64)*11) key
+
+		$awk '
+		BEGIN {
+			chars="'"$chars"'"
+			k=length(chars)
+
+			srand(); now = srand();
+			srand('$$' * 12 * 60 * 60 + now)
+
+			for (i = 0; i < 11; i++) {
+				printf "%c", substr(chars, int(rand()*k)+1, 1)
+			}
+			printf "\n"
+			exit
+		}'
+	fi
+}
 
 usage()
 {
@@ -107,6 +154,13 @@ usage()
 		echo >&2 "	no option for backend=$BACKEND_TYPE"
 	echo >&2 "  available metadata_backend: $backend_candidates (default is $backend_default)"
 
+	exit 1
+}
+
+ABORT()
+{
+	[ $# -gt 0 ] && echo >&2 "${PROGNAME}: $@"
+	echo >&2 "$PROGNAME failure"
 	exit 1
 }
 
@@ -203,8 +257,8 @@ display_plain_params()
 
     display_plain_params_backend_optional_$BACKEND_TYPE
 
-    echo "rc script for gfmd               : $RC_GFMD"
-    echo "rc script for backend            : $RC_BACKEND"
+    echo "rc script for gfmd               : $RC_DIR/gfmd"
+    echo "rc script for backend            : $RC_DIR/$RC_BACKEND_BASENAME"
     echo "gfmd conf file                   : $GFMD_CONF"
     if $PRIVATE_MODE; then
 	echo "gfsd conf file                   : $GFSD_CONF"
@@ -238,8 +292,8 @@ display_script_params()
 
     display_script_params_backend_optional_$BACKEND_TYPE
 
-    echo     "GFMD_RC=$RC_GFMD"
-    echo     "BACKEND_RC=$RC_BACKEND"
+    echo     "GFMD_RC=$RC_DIR/gfmd"
+    echo     "BACKEND_RC=$RC_DIR/$RC_BACKEND_BASENAME"
     echo     "GFMD_CONF=$GFMD_CONF"
     if $PRIVATE_MODE; then
 	echo     "GFSD_CONF=$GFSD_CONF"
@@ -391,6 +445,7 @@ set_default_backend_prefix_$BACKEND_TYPE
 #
 # default values
 #
+
 : ${CONFIG_PREFIX:=}
 
 set_first_defaults_$BACKEND_TYPE
@@ -399,15 +454,6 @@ set_first_defaults_$BACKEND_TYPE
 #	before calling sysdep_defaults
 # sysdep_defaults must set: $RC_DIR
 sysdep_defaults
-
-[ X"$RC_BACKEND" = X ] && \
-	: ${RC_BACKEND="$RC_DIR/$RC_BACKEND_BASENAME"}
-[ X"$RC_GFMD" = X ] && \
-	: ${RC_GFMD="$RC_DIR/gfmd"}
-[ X"$RC_AGENT" = X ] && \
-	: ${RC_AGENT="$RC_DIR/gfarm_agent"}
-[ X"$RC_GFSD" = X ] && \
-	: ${RC_GFSD="$RC_DIR/gfsd"}
 
 : ${START_SERVICE:=true}
 : ${FORCE:=false}
@@ -425,8 +471,6 @@ else
 fi
 : ${GFARM_CONF:="$GFARM_CONF_DIR/gfarm2.conf"}
 : ${GFMD_CONF:="$GFARM_CONF_DIR/gfmd.conf"}
-: ${UNCONFIG_SCRIPT:="$GFARM_CONF_DIR/unconfig-gfarm.sh"}
-: ${UNCONFIG_SCRIPT_IN:="$config_dir/unconfig-gfarm.sh.in"}
 if $PRIVATE_MODE; then
 	: ${GFSD_CONF:="$GFARM_CONF_DIR/gfsd.conf"}
 	: ${USERMAP_FILE:="$GFARM_CONF_DIR/usermap"}
@@ -451,7 +495,6 @@ fi
 : ${FQ_HOSTNAME:=`fq_hostname`}
 
 : ${BACKEND_HOSTNAME:="$FQ_HOSTNAME"}
-
 [ X$BACKEND_HOSTNAME = X ] &&
 	ABORT 'cannot determine metadata server hostname, please specify it by -h option'
 
@@ -516,41 +559,62 @@ _EOF_
 	)
 }
 
-unconfig_replace()
-{
-	# create $unconfig_script for "replace" command
-	(
-	    umask 077
-	    (
-		cat <<_EOF_
-s|@config_gfarm_datadir@|$datadir|g
-s|@config_gfarm_backend_type@|$BACKEND_TYPE|g
-s|@config_gfarm_rc_gfmd@|$RC_GFMD|g
-s|@config_gfarm_rc_backend@|$RC_BACKEND|g
-s|@rc_backend_basename@|$RC_BACKEND_BASENAME|g
-s|@config_gfarm_gfmd_config@|$GFMD_CONF|g
-s|@config_gfarm_gfarm_config@|$GFARM_CONF|g
-s|@config_gfarm_gfarm_config_dir@|$GFARM_CONF_DIR|g
-s|@config_gfarm_config_prefix@|$CONFIG_PREFIX|g
-s|@config_gfarm_backend_data_dir@|$BACKEND_DATA_DIR|g
-s|@config_gfarm_backend_log_dir@|$BACKEND_LOG_DIR|g
-s|@config_gfarm_gfmd_pid_file@|$GFMD_PID_FILE|g
-s|@config_gfarm_backend_pid_file@|$BACKEND_PID_FILE|g
-s|@config_gfarm_private_mode@|$PRIVATE_MODE|g
-s|@config_gfarm_usermap_file@|$USERMAP_FILE|g
-s|@config_gfarm_gfsd_config@|$GFSD_CONF|g
-s|@config_gfarm_metadata_replication@|$METADATA_REPLICATION|g
-s|@config_gfarm_metadata_journal_dir@|$METADATA_JOURNAL_DIR|g
-_EOF_
-	    ) > $sed_script
-	)
-
-	sed -f $sed_script ${1+"$@"}
-}
-
 replace()
 {
 	sed -f $sed_script ${1+"$@"} | config_sysdep
+}
+
+mkcnf()
+{
+	# local out
+
+	out=$1
+	shift
+	if ${1+"$@"} >$out; then
+		echo created $out
+	else
+		ABORT "cannot create $out"
+	fi
+}
+
+mkscript()
+{
+	mkcnf ${1+"$@"}
+	chmod +x "$1" || ABORT "cannot chmod +x $1"
+}
+
+delete_file_or_directory()
+{
+	# local p
+
+	for p
+	do
+		[ -d "$p" ] && rmdir "$p" > /dev/null 2>&1
+		# [ -e "$p" ] isn't portable. not supported by Solaris /bin/sh
+		if ls -1d "$p" >/dev/null 2>&1; then
+			if $FORCE; then
+				rm -rf "$p"
+				echo removed "$p"
+			else
+				ABORT "$p already exist"
+			fi
+		fi
+	done
+}
+
+create_directory()
+{
+	# local d
+
+	for d
+	do
+		[ -d "$d" ] && continue
+		if mkdir -p "$d"; then
+			echo created "$d"
+		else
+			ABORT "mkdir -p $d, failed"
+		fi
+	done
 }
 
 # most $BACKEND_TYPE uses the following as "init_replace_$BACKEND_TYPE"
@@ -563,7 +627,7 @@ delete_file_or_directory \
 	"$GFMD_CONF" \
 	"$BACKEND_DATA_DIR" \
 	"$BACKEND_LOG_DIR" \
-	"$RC_BACKEND"
+	"$RC_DIR/$RC_BACKEND_BASENAME"
 $METADATA_REPLICATION && \
 	delete_file_or_directory "$METADATA_JOURNAL_DIR"
 
@@ -653,9 +717,8 @@ if $PRIVATE_MODE; then
 fi
 
 # create run scripts
-create_run_script "$RC_BACKEND"	replace "$RC_BACKEND_IN"
-create_run_script "$RC_GFMD"	replace "$RC_GFMD_IN"
-$PRIVATE_MODE || service_reg $RC_BACKEND_BASENAME gfmd
+mkscript "$RC_DIR/$RC_BACKEND_BASENAME"	replace "$RC_BACKEND_IN"
+mkscript "$RC_DIR/gfmd"			replace "$RC_GFMD_IN"
 
 apply_configuration_$BACKEND_TYPE
 
@@ -667,11 +730,6 @@ if $START_SERVICE; then
 	service_ctl gfmd $ctl ||
 		ABORT "failed to $ctl gfmd"
 fi
-
-mkcnf "$UNCONFIG_SCRIPT" unconfig_replace "$UNCONFIG_SCRIPT_IN"
-chmod +x "$UNCONFIG_SCRIPT" || ABORT "cannot chmod +x $UNCONFIG_SCRIPT"
-
-rm -f $sed_script
 
 echo "$PROGNAME success"
 status=0
diff --git a/gftool/config-gfarm/config-gfsd.in b/gftool/config-gfarm/config-gfsd.in
--- a/gftool/config-gfarm/config-gfsd.in
+++ b/gftool/config-gfarm/config-gfsd.in
@@ -53,13 +53,18 @@ else
 	exit 1
 fi
 
-. $config_dir/config-gfarm.common
-
 usage()
 {
 	echo >&2 "usage: $PROGNAME [--help] [--prefix prefix] [-t|-T] [-f]"
 	echo >&2 "	[-a arch] [-p port] [-h hostname] [-n ncpu] "
 	echo >&2 "	[-l listen_address] [-S] [-N] spool_directory"
+	exit 1
+}
+
+ABORT()
+{
+	[ $# -gt 0 ] && echo >&2 "${PROGNAME}: $@"
+	echo >&2 "$PROGNAME failure"
 	exit 1
 }
 
@@ -87,7 +92,7 @@ display_plain_params()
 	echo "port                         [-p]: $GFSD_PORT"
 	echo "ncpu                         [-n]: $NCPU"
 	echo "spool directory                  : $SPOOL_DIRECTORY"
-	echo "rc script                        : $RC_GFSD"
+	echo "rc script                        : $RC_DIR/$RC_NAME"
 	echo "gfarm client conf file           : $GFARM_CLIENT_CONF"
 	if $PRIVATE_MODE; then
 		echo "gfsd conf file                   : $GFARM_CONF"
@@ -108,7 +113,7 @@ display_script_params()
 	echo "GFSD_PORT=$GFSD_PORT"
 	echo "NCPU=$NCPU"
 	echo "SPOOL_DIRECTORY=$SPOOL_DIRECTORY"
-	echo "GFSD_RC=$RC_GFSD"
+	echo "GFSD_RC=$RC_DIR/$RC_NAME"
 	echo "GFARM_CONF=$GFARM_CLIENT_CONF"
 	if $PRIVATE_MODE; then
 		echo "GFSD_CONF=$GFARM_CONF"
@@ -185,12 +190,6 @@ esac
 #
 
 : ${CONFIG_PREFIX:=}
-: ${LISTEN_ADDRESS:=""}
-if [ -n "$LISTEN_ADDRESS" ]; then
-	: ${GFSD_SERVICE_NAME:="gfsd-$LISTEN_ADDRESS"}
-else
-	: ${GFSD_SERVICE_NAME:="gfsd"}
-fi
 
 # NOTE: $CONFIG_PREFIX needs to be set before calling sysdep_defaults
 # sysdep_defaults must set: $RC_DIR
@@ -207,8 +206,6 @@ if [ X"$CONFIG_PREFIX" != X ]; then
 else
 	: ${GFARM_CONF_DIR:="$sysconfdir"}
 fi
-: ${UNCONFIG_SCRIPT:="$GFARM_CONF_DIR/unconfig-gfsd.sh"}
-: ${UNCONFIG_SCRIPT_IN:="$config_dir/unconfig-gfsd.sh.in"}
 if $PRIVATE_MODE; then
 	: ${GFARM_CONF:="$GFARM_CONF_DIR/gfsd.conf"}
 else
@@ -234,20 +231,23 @@ fi
 [ X"$ARCH" = X ] && ABORT 'cannot determine the architecture of this machine'
 
 : ${RC_GFSD_IN="$config_dir/gfsd.in"}
-: ${RC_GFSD:="$RC_DIR/$GFSD_SERVICE_NAME"}
+
+: ${LISTEN_ADDRESS:=""}
 
 if [ -n "$LISTEN_ADDRESS" ]; then
 	: ${SPOOL_DIRECTORY:="$CONFIG_PREFIX/var/gfarm-spool-$LISTEN_ADDRESS"}
 	: ${GFSD_EXTRA_OPTIONS:=" -l $LISTEN_ADDRESS"}
+	: ${RC_NAME:="gfsd-$LISTEN_ADDRESS"}
 	# $RC_VAR will be used as a shell variable name on *BSD ports & pkgsrc,
 	# thus, we only allow [0-9a-z_] as its value.
 	: ${RC_VAR:="`echo gfsd_$LISTEN_ADDRESS | sed 's/[^0-9a-z_]/_/g'`"}
 else
 	: ${SPOOL_DIRECTORY:="$CONFIG_PREFIX/var/gfarm-spool"}
 	: ${GFSD_EXTRA_OPTIONS:=""}
-	: ${RC_VAR:="$GFSD_SERVICE_NAME"}
+	: ${RC_NAME:="gfsd"}
+	: ${RC_VAR:="$RC_NAME"}
 fi
-: ${GFSD_PID_FILE:="$RUN_DIR/${GFSD_SERVICE_NAME}.pid"}
+: ${GFSD_PID_FILE:="$RUN_DIR/${RC_NAME}.pid"}
 
 # -t option; display parameters
 [ $PARAMS_DISPLAY_STYLE != none ] && display_${PARAMS_DISPLAY_STYLE}_params
@@ -263,29 +263,64 @@ config()
 	-e "s|@config_gfarm_globus_location@|${GLOBUS_LOCATION:-$globus_location}|g" \
 	-e "s|@config_gfarm_gfarm_config@|$GFARM_CONF|g" \
 	-e "s|@config_gfarm_gfsd_option@|-f $GFARM_CONF -h $GFSD_HOSTNAME -r $SPOOL_DIRECTORY$GFSD_EXTRA_OPTIONS|g" \
-	-e "s|@config_gfarm_gfsd_rc_name@|$GFSD_SERVICE_NAME|g" \
+	-e "s|@config_gfarm_gfsd_rc_name@|$RC_NAME|g" \
 	-e "s|@config_gfarm_gfsd_rc_var@|$RC_VAR|g" \
 	-e "s|@config_gfarm_gfsd_pid_file@|$GFSD_PID_FILE|g" \
 	-e "s|@config_gfarm_run_dir@|$RUN_DIR|g" \
 	${1+"$@"} | config_sysdep
 }
 
-unconfig()
+mkcnf()
 {
-	sed \
-	-e "s|@config_gfarm_prefix@|$prefix|g" \
-	-e "s|@config_gfarm_datadir@|$datadir|g" \
-	-e "s|@config_gfarm_spool_directory@|$SPOOL_DIRECTORY|g" \
-	-e "s|@config_gfarm_rc_gfsd@|$RC_GFSD|g" \
-	-e "s|@config_gfarm_gfsd_pid_file@|$GFSD_PID_FILE|g" \
-	-e "s|@config_gfarm_gfarm_config@|$GFARM_CONF|g" \
-	-e "s|@config_gfarm_gfarm_client_config@|$GFARM_CLIENT_CONF|g" \
-	-e "s|@config_gfarm_gfarm_conf_dir@|$GFARM_CONF_DIR|g" \
-	-e "s|@config_gfarm_config_prefix@|$CONFIG_PREFIX|g" \
-        -e "s|@config_gfarm_private_mode@|$PRIVATE_MODE|g" \
-	-e "s|@config_gfarm_usermap_file@|$USERMAP_FILE|g" \
-	-e "s|@config_gfarm_gfsd_hostname@|$GFSD_HOSTNAME|g" \
-	${1+"$@"}
+	# local out
+
+	out=$1
+	shift
+	if ${1+"$@"} >$out; then
+		echo created $out
+	else
+		ABORT "cannot create $out"
+	fi
+}
+
+mkscript()
+{
+	mkcnf ${1+"$@"}
+	chmod +x "$1" || ABORT "cannot chmod +x $1"
+}
+
+delete_file_or_directory()
+{
+	# local p
+
+	for p
+	do
+		[ -d "$p" ] && rmdir "$p" > /dev/null 2>&1
+		# [ -e "$p" ] isn't portable. not supported by Solaris /bin/sh
+		if ls -1d "$p" >/dev/null 2>&1; then
+			if $FORCE; then
+				rm -rf "$p"
+				echo removed "$p"
+			else
+				ABORT "$p already exist"
+			fi
+		fi
+	done
+}
+
+create_directory()
+{
+	# local d
+
+	for d
+	do
+		[ -d "$d" ] && continue
+		if mkdir -p "$d"; then
+			echo created "$d"
+		else
+			ABORT "mkdir -p $d, failed"
+		fi
+	done
 }
 
 #########################################################################
@@ -308,11 +343,7 @@ fi
 mkcnf_gfsd_sysdep
 
 # create run scripts
-create_run_script "$RC_GFSD"	config "$RC_GFSD_IN"
-$PRIVATE_MODE || service_reg gfsd
-
-mkcnf "$UNCONFIG_SCRIPT"	unconfig "$UNCONFIG_SCRIPT_IN"
-chmod +x "$UNCONFIG_SCRIPT" || ABORT "cannot chmod +x $UNCONFIG_SCRIPT"
+mkscript $RC_DIR/$RC_NAME	config "$RC_GFSD_IN"
 
 # update configuration file
 # spool_check_level (default value)
@@ -339,9 +370,9 @@ echo >&2 "gfhost -c -a $ARCH -p $GFSD_PORT -n $NCPU $GFSD_HOSTNAME: failed"
 
 if $START_SERVICE; then
 	if [ -f $GFSD_PID_FILE ]; then ctl=restart; else ctl=start; fi
-	service_add $GFSD_SERVICE_NAME &&
-		service_ctl $GFSD_SERVICE_NAME $ctl ||
-		ABORT "failed to $ctl $GFSD_SERVICE_NAME"
+	service_add $RC_NAME &&
+		service_ctl $RC_NAME $ctl ||
+		ABORT "failed to $ctl $RC_NAME"
 fi
 echo "$PROGNAME success"
 
@@ -355,7 +386,8 @@ echo "$prefix/bin/gfhost" -c -a $ARCH -p $GFSD_PORT -n $NCPU $GFSD_HOSTNAME
 echo
 echo After that, start gfsd by the following command as a root:
 echo
-service_ctl -n $GFSD_SERVICE_NAME start
-fi
+# XXX FIXME should use "forcestart" instead of "start" on NetBSD and FreeBSD.
+echo "$RC_DIR/$RC_NAME start"
 
+fi
 exit 0
